[MeterRotator1]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator2]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator3]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator4]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator5]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator6]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator7]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator8]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator9]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator10]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator11]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator12]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator13]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator14]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator15]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator16]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator17]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator18]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator19]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator20]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator21]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator22]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator23]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator24]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator25]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator26]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator27]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator28]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator29]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator30]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator31]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator32]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator33]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator34]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator35]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator36]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator37]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator38]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator39]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator40]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator41]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator42]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator43]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator44]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator45]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator46]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator47]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator48]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator49]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator50]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator51]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator52]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator53]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator54]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator55]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator56]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator57]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator58]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator59]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator60]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator61]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator62]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator63]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator64]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator65]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator66]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator67]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator68]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator69]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator70]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator71]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator72]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator73]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator74]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator75]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator76]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator77]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator78]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator79]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator80]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator81]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator82]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator83]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator84]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator85]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator86]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator87]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator88]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator89]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator90]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator91]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator92]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator93]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator94]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator95]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator96]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator97]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator98]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator99]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator100]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator101]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator102]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator103]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator104]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator105]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator106]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator107]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator108]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator109]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator110]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator111]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator112]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator113]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator114]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator115]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator116]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator117]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator118]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator119]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator120]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator121]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator122]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator123]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator124]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator125]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator126]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator127]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator128]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator129]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator130]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator131]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator132]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator133]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator134]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator135]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator136]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator137]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator138]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator139]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator140]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator141]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator142]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator143]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator144]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator145]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator146]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator147]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator148]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator149]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator150]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator151]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator152]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator153]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator154]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator155]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator156]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator157]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator158]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator159]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator160]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator161]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator162]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator163]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator164]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator165]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator166]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator167]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator168]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator169]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator170]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator171]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator172]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator173]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator174]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator175]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator176]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator177]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator178]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator179]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator180]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator181]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator182]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator183]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator184]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator185]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator186]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator187]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator188]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator189]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator190]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator191]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator192]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator193]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator194]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator195]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator196]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator197]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator198]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator199]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator200]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator201]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator202]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator203]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator204]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator205]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator206]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator207]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator208]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator209]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator210]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator211]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator212]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator213]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator214]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator215]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator216]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator217]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator218]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator219]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator220]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator221]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator222]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator223]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator224]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator225]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator226]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator227]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator228]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator229]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator230]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator231]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator232]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator233]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator234]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator235]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator236]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator237]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator238]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator239]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator240]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator241]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator242]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator243]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator244]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator245]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator246]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator247]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator248]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator249]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator250]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator251]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator252]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator253]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator254]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator255]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator256]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator257]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator258]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator259]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator260]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator261]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator262]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator263]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator264]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator265]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator266]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator267]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator268]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator269]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator270]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator271]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator272]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator273]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator274]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator275]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator276]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator277]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator278]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator279]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator280]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator281]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator282]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator283]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator284]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator285]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator286]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator287]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator288]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator289]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator290]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator291]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator292]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator293]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator294]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator295]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator296]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator297]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator298]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator299]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator300]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator301]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator302]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator303]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator304]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator305]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator306]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator307]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator308]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator309]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator310]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator311]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator312]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator313]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator314]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator315]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator316]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator317]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator318]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator319]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator320]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator321]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator322]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator323]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator324]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator325]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator326]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator327]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator328]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator329]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator330]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator331]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator332]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator333]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator334]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator335]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator336]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator337]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator338]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator339]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator340]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator341]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator342]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator343]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator344]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator345]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator346]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator347]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator348]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator349]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator350]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator351]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator352]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator353]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator354]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator355]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator356]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator357]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator358]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator359]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator360]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator361]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator362]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator363]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator364]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator365]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator366]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator367]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator368]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator369]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator370]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator371]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator372]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator373]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator374]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator375]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator376]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator377]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator378]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator379]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator380]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator381]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator382]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator383]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator384]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator385]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator386]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator387]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator388]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator389]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator390]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator391]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator392]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator393]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator394]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator395]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator396]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator397]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator398]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator399]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator400]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator401]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator402]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator403]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator404]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator405]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator406]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator407]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator408]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator409]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator410]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator411]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator412]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator413]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator414]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator415]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator416]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator417]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator418]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator419]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator420]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator421]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator422]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator423]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator424]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator425]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator426]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator427]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator428]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator429]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator430]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator431]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator432]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator433]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator434]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator435]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator436]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator437]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator438]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator439]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator440]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator441]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator442]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator443]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator444]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator445]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator446]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator447]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator448]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator449]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator450]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator451]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator452]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator453]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator454]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator455]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator456]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator457]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator458]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator459]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator460]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator461]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator462]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator463]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator464]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator465]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator466]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator467]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator468]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator469]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator470]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator471]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator472]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator473]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator474]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator475]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator476]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator477]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator478]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator479]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator480]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator481]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator482]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator483]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator484]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator485]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator486]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator487]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator488]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator489]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator490]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator491]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator492]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator493]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator494]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator495]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator496]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator497]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator498]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator499]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator500]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator501]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator502]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator503]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator504]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator505]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator506]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator507]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator508]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator509]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator510]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator511]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator512]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator513]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator514]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator515]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator516]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator517]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator518]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator519]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator520]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator521]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator522]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator523]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator524]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator525]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator526]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator527]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator528]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator529]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator530]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator531]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator532]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator533]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator534]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator535]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator536]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator537]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator538]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator539]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator540]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator541]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator542]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator543]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator544]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator545]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator546]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator547]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator548]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator549]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator550]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator551]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator552]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator553]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator554]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator555]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator556]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator557]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator558]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator559]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator560]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator561]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator562]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator563]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator564]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator565]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator566]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator567]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator568]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator569]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator570]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator571]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator572]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator573]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator574]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator575]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator576]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator577]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator578]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator579]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator580]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator581]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator582]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator583]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator584]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator585]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator586]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator587]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator588]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator589]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator590]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator591]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator592]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator593]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator594]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator595]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator596]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator597]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator598]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator599]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator600]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator601]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator602]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator603]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator604]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator605]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator606]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator607]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator608]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator609]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator610]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator611]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator612]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator613]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator614]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator615]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator616]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator617]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator618]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator619]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator620]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator621]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator622]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator623]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator624]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator625]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator626]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator627]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator628]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator629]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator630]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator631]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator632]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator633]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator634]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator635]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator636]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator637]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator638]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator639]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator640]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator641]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator642]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator643]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator644]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator645]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator646]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator647]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator648]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator649]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator650]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator651]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator652]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator653]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator654]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator655]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator656]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator657]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator658]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator659]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator660]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator661]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator662]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator663]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator664]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator665]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator666]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator667]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator668]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator669]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator670]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator671]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator672]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator673]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator674]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator675]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator676]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator677]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator678]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator679]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator680]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator681]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator682]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator683]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator684]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator685]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator686]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator687]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator688]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator689]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator690]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator691]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator692]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator693]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator694]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator695]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator696]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator697]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator698]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator699]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator700]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator701]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator702]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator703]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator704]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator705]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator706]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator707]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator708]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator709]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator710]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator711]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator712]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator713]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator714]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator715]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator716]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator717]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator718]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator719]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator720]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator721]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator722]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator723]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator724]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator725]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator726]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator727]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator728]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator729]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator730]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator731]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator732]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator733]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator734]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator735]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator736]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator737]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator738]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator739]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator740]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator741]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator742]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator743]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator744]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator745]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator746]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator747]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator748]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator749]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator750]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator751]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator752]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator753]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator754]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator755]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator756]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator757]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator758]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator759]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator760]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator761]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator762]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator763]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator764]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator765]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator766]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator767]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator768]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator769]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator770]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator771]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator772]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator773]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator774]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator775]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator776]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator777]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator778]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator779]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator780]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator781]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator782]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator783]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator784]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator785]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator786]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator787]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator788]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator789]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator790]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator791]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator792]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator793]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator794]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator795]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator796]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator797]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator798]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator799]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator800]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator801]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator802]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator803]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator804]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator805]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator806]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator807]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator808]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator809]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator810]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator811]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator812]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator813]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator814]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator815]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator816]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator817]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator818]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator819]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator820]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator821]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator822]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator823]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator824]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator825]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator826]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator827]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator828]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator829]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator830]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator831]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator832]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator833]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator834]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator835]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator836]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator837]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator838]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator839]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator840]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator841]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator842]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator843]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator844]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator845]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator846]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator847]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator848]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator849]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator850]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator851]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator852]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator853]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator854]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator855]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator856]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator857]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator858]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator859]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator860]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator861]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator862]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator863]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator864]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator865]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator866]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator867]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator868]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator869]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator870]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator871]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator872]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator873]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator874]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator875]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator876]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator877]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator878]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator879]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator880]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator881]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator882]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator883]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator884]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator885]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator886]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator887]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator888]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator889]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator890]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator891]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator892]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator893]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator894]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator895]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator896]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator897]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator898]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator899]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator900]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator901]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator902]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator903]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator904]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator905]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator906]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator907]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator908]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator909]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator910]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator911]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator912]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator913]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator914]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator915]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator916]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator917]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator918]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator919]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator920]
Meter=Rotator
MeasureName=MeasureZero